# Generated by Django 4.2.2 on 2023-07-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-reported_date']},
        ),
    ]
