# Generated by Django 4.2.2 on 2023-06-28 06:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preparation', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_host', to=settings.AUTH_USER_MODEL)),
                ('panitia_ids', models.ManyToManyField(related_name='events_panitia', to=settings.AUTH_USER_MODEL)),
                ('support_ids', models.ManyToManyField(related_name='events_support', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
