# Generated by Django 4.2.2 on 2023-06-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host_id',
            new_name='host',
        ),
    ]
