# Generated by Django 4.2.2 on 2023-07-01 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_event_is_deleted_alter_event_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='staffs',
            field=models.ManyToManyField(related_name='events_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
