# Generated by Django 4.2.2 on 2023-07-26 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('link_id', models.IntegerField(primary_key=True, serialize=False)),
                ('link_url', models.URLField()),
                ('title', models.CharField()),
                ('type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MULTIPLE', 'MULTIPLE')])),
                ('amount', models.IntegerField()),
                ('redirect_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')])),
                ('expired_date', models.DateTimeField(null=True)),
                ('created_from', models.CharField()),
                ('is_address_required', models.BooleanField()),
                ('is_phone_number_required', models.BooleanField()),
                ('step', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.payment'),
        ),
    ]
