# Generated by Django 4.2.2 on 2023-07-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link_url',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='redirect_url',
            field=models.CharField(blank=True),
        ),
    ]
