# Generated by Django 4.2.2 on 2023-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_payment_link_url_alter_payment_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_donation',
            field=models.IntegerField(default=0),
        ),
    ]
