# Generated by Django 4.2.2 on 2023-07-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_payment_total_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_donation',
        ),
        migrations.AddField(
            model_name='event',
            name='total_donation',
            field=models.IntegerField(default=0),
        ),
    ]
