# Generated by Django 4.2.2 on 2023-07-27 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_event_account_number_alter_event_bank_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('bank_code', models.CharField()),
                ('account_number', models.CharField()),
                ('recipient_name', models.CharField()),
                ('fee', models.IntegerField()),
                ('beneficiary_email', models.TextField()),
                ('idempotency_key', models.CharField()),
            ],
            options={
                'unique_together': {('id', 'is_deleted')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='disbursement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.disbursement'),
        ),
    ]
