# Generated by Django 4.2.2 on 2023-07-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_disbursement_event_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='receipt',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='status',
            field=models.CharField(default='PENDING'),
            preserve_default=False,
        ),
    ]
