# Generated by Django 4.2.2 on 2023-07-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_geolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
