# Generated by Django 4.2.2 on 2023-07-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_geolocation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'ordering': ['name']},
        ),
    ]
