# Generated by Django 4.2.2 on 2023-06-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_event_ids',
            field=models.ManyToManyField(related_name='joined_user_ids', to='event.event'),
        ),
    ]
