name: ci

on:
  push:
    branches:
      - "feat/deployment-v2"
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_NAME }}:${{ secrets.DOCKER_IMAGE_TAG }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy with Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_ADDRESS }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            docker container rm -f ${{ secrets.DOCKER_REGISTRY_NAME }} \
            && docker image rm -f ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_NAME }}:${{ secrets.DOCKER_IMAGE_TAG }} \
            && docker run -e ${{ secrets.ENV_FILE }} -p 8001:8000 -d ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_NAME }}:${{ secrets.DOCKER_IMAGE_TAG }} \
            && docker container ls -n 1